// Generated by CoffeeScript 1.4.0
(function() {

  this.CalculationRow = (function() {

    function CalculationRow(lineNumber, operator, values) {
      this.lineNumber = lineNumber;
      this.operator = operator;
      this.values = values;
    }

    CalculationRow.prototype.calculate = function() {
      switch (this.operator) {
        case "SUM":
          return go(sum);
        case "MIN":
          return go(min);
        case "MAX":
          return go(max);
        case "AVERAGE":
          return go(average);
      }
    };

    CalculationRow.prototype.sum = function() {
      return this.values.reduce(t, s)(function() {
        return t + s;
      });
    };

    CalculationRow.prototype.min = function() {
      return this.values.reduce(t, s)(function() {
        return Math.min(t, s);
      });
    };

    CalculationRow.prototype.max = function() {
      return this.values.reduce(t, s)(function() {
        return Math.max(t, s);
      });
    };

    CalculationRow.prototype.average = function() {
      return (this.values.reduce(t, s, 0)(function() {
        return t += s;
      })) / this.values.length;
    };

    return CalculationRow;

  })();

  this.validateInput = function(inputString) {
    var validRegex;
    validRegex = /(\d\#-(\bSUM\b|\bAVERAGE\b|\bMIN\b|\bMAX\b):(\s*\d+)(,\s*\d+\s*)*)/;
    return !!inputString && validRegex.test(inputString.toUpperCase());
  };

  this.stripWhiteSpaceAndChangeToUpper = function(inputString) {
    return inputString.replace(/^\s+|s+$/g, "");
  };

  this.parseInputText = function(inputString) {
    var rows;
    return rows = inputString.match(/\r\n|[\n\v\f\r\x85\u2028\u2029]/);
  };

}).call(this);
